# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD para React com Vercel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cypress run
      user: cypress-io/github-action@6
      with:
        command: yarn cy :run
        start: yarn start
      env:
        CI: false

    -name: Install Vercel CLI
      run: npm install --global vercel@latest
    -name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    -name: Build Projects Artifacts
      run: vercel build --prod --tokens=${{ secrets.VERCEL_TOKEN }}
    -name: Deploy Project Artifacts To Vercel
      run: vercel deploy --prebuilt --prod --tokens=${{ secrets.VERCEL_TOKEN }}
